def exception_safe(f):
    pass # TODO
